# docker-compose.yml
services:
  mongo:
    image: mongo:7
    container_name: mongo-rs
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
